package com.kesdip.designer.properties;

import org.eclipse.jface.dialogs.MessageDialog;
import org.eclipse.jface.viewers.TextCellEditor;
import org.eclipse.swt.events.FocusAdapter;
import org.eclipse.swt.events.FocusEvent;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;

public class ValidatingTextCellEditor extends TextCellEditor {
	
	private Composite ancestor;
	private String errorMessage;
	
	/**
	 * Sets the error message displayed by the cell editor. If left null, the original error message
	 * generated by the validator will be displayed.
	 */
	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}
	
	public ValidatingTextCellEditor() {
		super();
	}
	
	public ValidatingTextCellEditor(Composite parent) {
		super(parent);
	}
	
	public ValidatingTextCellEditor(Composite parent, int style) {
		super(parent, style);
	}

	@Override
	protected Control createControl(Composite parent) {
		ancestor = parent;
		Control retVal = super.createControl(parent);
		retVal.addFocusListener(new FocusAdapter() {
			@Override
			public void focusLost(FocusEvent e) {
				if (getErrorMessage() != null) {
					MessageDialog.openError(ancestor.getShell(),
							errorMessage == null ? "Error" : errorMessage, getErrorMessage());
				}
				super.focusLost(e);
			}
		});
		return retVal;
	}

	
}
